# Generated by Django 4.0 on 2022-07-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelshoppingcar',
            name='price',
            field=models.IntegerField(),
        ),
    ]
